-- begin HELPDESK_REGION
create unique index IDX_HELPDESK_REGION_UK_NAME on HELPDESK_REGION (NAME) where DELETE_TS is null ^
create unique index IDX_HELPDESK_REGION_UK_CODE on HELPDESK_REGION (CODE) where DELETE_TS is null ^
-- end HELPDESK_REGION
-- begin HELPDESK_DEVICE
alter table HELPDESK_DEVICE add constraint FK_HELPDESK_DEVICE_ON_VENDOR foreign key (VENDOR_ID) references HELPDESK_VENDOR(ID)^
create unique index IDX_HELPDESK_DEVICE_UK_CODE on HELPDESK_DEVICE (CODE) where DELETE_TS is null ^
create index IDX_HELPDESK_DEVICE_ON_VENDOR on HELPDESK_DEVICE (VENDOR_ID)^
-- end HELPDESK_DEVICE
-- begin HELPDESK_CUSTOMER
alter table HELPDESK_CUSTOMER add constraint FK_HELPDESK_CUSTOMER_ON_COUNTRY foreign key (COUNTRY_ID) references HELPDESK_COUNTRY(ID)^
alter table HELPDESK_CUSTOMER add constraint FK_HELPDESK_CUSTOMER_ON_REGION foreign key (REGION_ID) references HELPDESK_REGION(ID)^
create index IDX_HELPDESK_CUSTOMER_ON_COUNTRY on HELPDESK_CUSTOMER (COUNTRY_ID)^
create index IDX_HELPDESK_CUSTOMER_ON_REGION on HELPDESK_CUSTOMER (REGION_ID)^
-- end HELPDESK_CUSTOMER
-- begin HELPDESK_SOFTWARE
alter table HELPDESK_SOFTWARE add constraint FK_HELPDESK_SOFTWARE_ON_VENDOR foreign key (VENDOR_ID) references HELPDESK_VENDOR(ID)^
create index IDX_HELPDESK_SOFTWARE_ON_VENDOR on HELPDESK_SOFTWARE (VENDOR_ID)^
-- end HELPDESK_SOFTWARE
-- begin HELPDESK_TOWN
create unique index IDX_HELPDESK_TOWN_UK_NAME on HELPDESK_TOWN (NAME) where DELETE_TS is null ^
-- end HELPDESK_TOWN
